/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Responsive WebP variants of the product JPEGs, generated by `npm run images`
// (scripts/optimize-images.mjs). Widths must match that script.

const WIDTHS = [480, 720, 1200];

/** "/images/foo.jpg" -> "/images/foo-480.webp 480w, /images/foo-720.webp 720w, ..." */
export const webpSrcSet = (jpg: string) =>
  WIDTHS.map((w) => `${jpg.replace(/\.jpg$/, `-${w}.webp`)} ${w}w`).join(", ");

// Rendered width of product photography: half the 1280px container on desktop,
// full width minus the 24px gutters on mobile.
export const PRODUCT_IMAGE_SIZES = "(min-width: 1024px) 580px, calc(100vw - 48px)";
